### PR TITLE
Update service.py

### PR DESCRIPTION
**Pull request by Richiio**
Rectified the null null error

### CODE REVIEW

**Comment by GemmaTuron** [comment]
@Richiio thanks, I've left a comment on the model issue discussion for your review

**Comment by Richiio** [comment]
Hi @GemmaTuron It's been rectified

**Comment by GemmaTuron** [comment]
Hi @Richiio 

Please try to abide as much as possible with the existing framework for the Ersilia Models. 
The main.py already contains code to load the input file that comes from standard processing in Ersilia, so keep that as is, do not create a new function:

# Functions
```
def Fingerprint_compute(Smi):
    try:
        mol = Chem.MolFromSmiles(Smi)
        fp_hash = AllChem.GetMorganFingerprintAsBitVect(mol,2,nBits=1024)
        fp = fp_hash.ToBitString()
        return fp
    except:
        return 'error'

def Compute(df):
    length = len(df)
    List_smiles = df.iloc[:, 0]

    List_fp = []
    for i in range(0,length):
        smi = List_smiles[i]
        if smi == 'error':
            continue
        else:
            fp = Fingerprint_compute(smi)
            fp_split = list(str(fp))
            List_fp.append(fp_split)
    df_fp = pd.DataFrame(List_fp)
    return df_fp

def class_type2(class_pre): # we do not need this function here
    flag = 'Inactive'
    if class_pre == 1:
        flag = 'Active'
    return flag

def predict_class(input_file, model_pre, output_file): #please modify this to use only a list of smiles, as is done in the ersilia default main.py
    df_input = pd.read_csv(input_file)
    df_pre = Compute(df_input)
    X = np.array(df_pre)
    proba_pre = model_pre.predict_proba(X)
    list_active = [x[1] for x in proba_pre]

    df_result = pd.DataFrame({
        'Probability_active': list_active
    })

    df_result.to_csv(output_file, index=None) #do not pass a .csv file as output, but only a list of probas. USe the default Ersilia main.py to give the final file
```

**Comment by GemmaTuron** [comment]
Also @Richiio please update the metadata file with the following description:
_The model predicts the inhibitory potential of small molecules against Histone deacetylase 3 (HDAC3), a relevant human target for cancer, inflammation, neurodegenerative diseases and diabetes. The authors have used a dataset of 1098 compounds from ChEMBL and validated the model using the benchmark MUBD-HDAC3._
And the interpretation should also be updated since we are giving probabilities:
_Probability that the molecule is a HDAC3 inhibitor_

**Comment by GemmaTuron** [comment]
thanks for the changes @Richiio good job!

**Comment by Richiio** [comment]
Thanks @GemmaTuron

**Pull request merged**
